# Generated by Django 5.0 on 2024-07-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="peso",
            field=models.CharField(default=0, max_length=100),
        ),
    ]
