# Generated by Django 5.0 on 2024-07-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0002_produto_peso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="peso",
            field=models.IntegerField(default=0),
        ),
    ]
